name: presentation_displays
description: Flutter plugin supports to run on two screens. It's basically a tablet connected to another screen via an HDMI or Wireless
homepage: https://github.com/VNAPNIC/presentation-displays
version: 0.1.3
author: vn.apnic@gmail.com

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.10.0"

dependencies:
  flutter:
    sdk: flutter
  pedantic: ^1.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.namit.presentation_displays
        pluginClass: PresentationDisplaysPlugin
      ios:
        pluginClass: PresentationDisplaysPlugin